# Generated by Django 6.0 on 2025-12-31 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to add deletion token to PeriodAssignment and create CollectionMaintainer model."""

    dependencies = [
        ("adoration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodassignment",
            name="deletion_token",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="CollectionMaintainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adoration.collection",
                    ),
                ),
                (
                    "maintainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adoration.maintainer",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("collection", "maintainer"),
                        name="collection_maintainer_unique_constraint",
                    )
                ],
            },
        ),
    ]
