# Generated by Django 6.0 on 2026-01-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add privacy fields to PeriodAssignment model."""

    dependencies = [
        ("adoration", "0002_periodassignment_deletion_token_collectionmaintainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodassignment",
            name="email_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="periodassignment",
            name="salt",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="periodassignment",
            name="attendant_email",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="periodassignment",
            name="attendant_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
