# Generated by Django 6.0 on 2026-01-02 21:53

import hashlib
import secrets

from django.db import migrations


def transform_existing_assignments(apps, schema_editor):
    """Transform existing PeriodAssignment data to use hashed emails.

    Args:
        apps: Django apps registry
        schema_editor: Database schema editor
    """
    PeriodAssignment = apps.get_model("adoration", "PeriodAssignment")

    for assignment in PeriodAssignment.objects.all():
        if assignment.attendant_email and not assignment.email_hash:
            # Generate salt and deletion token
            salt = secrets.token_hex(16)  # 32 character hex string

            # Generate deletion token if not exists
            if not assignment.deletion_token:
                random_token = secrets.token_urlsafe(48)
                assignment.deletion_token = hashlib.sha256(random_token.encode()).hexdigest()

            # Create email hash with salt and deletion token
            combined_data = f"{assignment.attendant_email}{salt}{assignment.deletion_token}"
            email_hash = hashlib.sha256(combined_data.encode()).hexdigest()

            # Update the assignment
            assignment.salt = salt
            assignment.email_hash = email_hash
            assignment.save()


def reverse_transform(apps, schema_editor):
    """Reverse transformation - not possible to recover original emails.

    Args:
        apps: Django apps registry
        schema_editor: Database schema editor
    """
    # Cannot reverse this transformation as we're removing the original email data
    pass


class Migration(migrations.Migration):
    """Transform existing email data to use hashed format for privacy."""

    dependencies = [
        ("adoration", "0003_add_privacy_fields"),
    ]

    operations = [
        migrations.RunPython(transform_existing_assignments, reverse_transform),
    ]
