# Generated by Django 6.0 on 2026-01-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    """Finalize privacy fields by removing old email field."""

    dependencies = [
        ("adoration", "0004_transform_existing_data"),
    ]

    operations = [
        # Make new fields non-nullable
        migrations.AlterField(
            model_name="periodassignment",
            name="email_hash",
            field=models.CharField(max_length=64, blank=False, null=False),
        ),
        migrations.AlterField(
            model_name="periodassignment",
            name="salt",
            field=models.CharField(max_length=32, blank=False, null=False),
        ),
        migrations.AlterField(
            model_name="periodassignment",
            name="deletion_token",
            field=models.CharField(max_length=128, unique=True, blank=False, null=False),
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name="periodassignment",
            name="attendant_name",
        ),
        migrations.RemoveField(
            model_name="periodassignment",
            name="attendant_email",
        ),
        migrations.RemoveField(
            model_name="periodassignment",
            name="attendant_phone_number",
        ),
    ]
