# Generated by Django 6.0 on 2026-01-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to add available_languages field to Collection model."""

    dependencies = [
        ("adoration", "0005_finalize_privacy_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="available_languages",
            field=models.JSONField(
                default=list,
                help_text="List of language codes this collection is available in (e.g., ['en', 'pl', 'nl'])",
            ),
        ),
    ]
