# Generated by Django 6.0 on 2026-01-03 22:00

from django.conf import settings
from django.db import migrations


def populate_collection_languages_forward(apps, schema_editor):
    """Populate existing collections with default available languages.

    Args:
        apps: Django apps registry
        schema_editor: Database schema editor
    """
    Collection = apps.get_model("adoration", "Collection")

    # Get all configured language codes
    default_languages = [code for code, name in settings.LANGUAGES]

    # Update all existing collections that don't have languages set
    collections_to_update = Collection.objects.filter(available_languages__isnull=True) | Collection.objects.filter(
        available_languages=[]
    )

    for collection in collections_to_update:
        collection.available_languages = default_languages
        collection.save(update_fields=["available_languages"])


def populate_collection_languages_reverse(apps, schema_editor):
    """Reverse migration - clear available_languages field.

    Args:
        apps: Django apps registry
        schema_editor: Database schema editor
    """
    Collection = apps.get_model("adoration", "Collection")

    # Clear all available_languages fields
    Collection.objects.all().update(available_languages=[])


class Migration(migrations.Migration):
    """Migration to populate collection languages with default values."""

    dependencies = [
        ("adoration", "0006_collection_available_languages"),
    ]

    operations = [
        migrations.RunPython(
            populate_collection_languages_forward,
            populate_collection_languages_reverse,
        ),
    ]
