# Generated by Django 6.0 on 2026-01-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add iterations field to PeriodAssignment model for PBKDF2 hashing."""

    dependencies = [
        ("adoration", "0007_auto_20260103_2200"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodassignment",
            name="iterations",
            field=models.IntegerField(
                default=320000,
                help_text="Number of PBKDF2 iterations used for email hashing",
            ),
        ),
    ]
