# Generated by Django 6.0 on 2026-01-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    """Update email_hash field to accommodate longer PBKDF2 hashes."""

    dependencies = [
        ("adoration", "0008_add_iterations_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodassignment",
            name="email_hash",
            field=models.CharField(max_length=128, blank=False, null=False),
        ),
    ]
