# Generated by Django 6.0 on 2026-01-03 22:45

from django.db import migrations


def remove_old_assignments(apps, schema_editor):
    """Remove all existing period assignments with old SHA256 hashes.

    This is necessary because the hashing algorithm changed from SHA256 to PBKDF2,
    making existing email hashes incompatible with the new verification system.

    Args:
        apps: Django apps registry
        schema_editor: Database schema editor
    """
    PeriodAssignment = apps.get_model("adoration", "PeriodAssignment")

    # Remove all existing assignments
    count = PeriodAssignment.objects.count()
    PeriodAssignment.objects.all().delete()

    print(f"Removed {count} existing period assignments due to hash algorithm change.")


def reverse_remove_old_assignments(apps, schema_editor):
    """Reverse migration - cannot restore deleted assignments.

    Args:
        apps: Django apps registry
        schema_editor: Database schema editor
    """
    # Cannot reverse this operation as we deleted the data
    print("WARNING: Cannot restore deleted period assignments.")
    pass


class Migration(migrations.Migration):
    """Remove all existing period assignments due to hash algorithm change."""

    dependencies = [
        ("adoration", "0009_update_email_hash_field"),
    ]

    operations = [
        migrations.RunPython(remove_old_assignments, reverse_remove_old_assignments),
    ]
