# Generated by Django 6.0 on 2026-01-03 23:00

from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def create_maintainer_permissions(apps, schema_editor):
    """Create maintainer group and assign appropriate permissions.

    Args:
        apps: Django apps registry
        schema_editor: Database schema editor
    """
    # Get models
    Collection = apps.get_model("adoration", "Collection")
    Period = apps.get_model("adoration", "Period")
    PeriodCollection = apps.get_model("adoration", "PeriodCollection")
    PeriodAssignment = apps.get_model("adoration", "PeriodAssignment")
    Maintainer = apps.get_model("adoration", "Maintainer")
    CollectionMaintainer = apps.get_model("adoration", "CollectionMaintainer")

    # Create or get the maintainer group
    maintainer_group, created = Group.objects.get_or_create(name="Maintainers")

    # Define permissions to assign to maintainers
    permission_codenames = [
        # Collection permissions
        "add_collection",
        "change_collection",
        "delete_collection",
        "view_collection",
        # Period permissions
        "add_period",
        "change_period",
        "delete_period",
        "view_period",
        # PeriodCollection permissions
        "add_periodcollection",
        "change_periodcollection",
        "delete_periodcollection",
        "view_periodcollection",
        # PeriodAssignment permissions
        "view_periodassignment",
        "delete_periodassignment",
        # Maintainer permissions
        "add_maintainer",
        "change_maintainer",
        "view_maintainer",
        # CollectionMaintainer permissions
        "add_collectionmaintainer",
        "change_collectionmaintainer",
        "delete_collectionmaintainer",
        "view_collectionmaintainer",
    ]

    # Get content types for our models
    content_types = {
        "collection": ContentType.objects.get_for_model(Collection),
        "period": ContentType.objects.get_for_model(Period),
        "periodcollection": ContentType.objects.get_for_model(PeriodCollection),
        "periodassignment": ContentType.objects.get_for_model(PeriodAssignment),
        "maintainer": ContentType.objects.get_for_model(Maintainer),
        "collectionmaintainer": ContentType.objects.get_for_model(CollectionMaintainer),
    }

    # Get or create permissions and add to maintainer group
    permissions = []
    for codename in permission_codenames:
        # Extract model name from codename
        action, model_name = codename.split("_", 1)

        # Get the content type
        content_type = content_types.get(model_name)
        if content_type:
            permission, perm_created = Permission.objects.get_or_create(
                codename=codename,
                content_type=content_type,
                defaults={
                    "name": f"Can {action} {model_name}",
                },
            )
            permissions.append(permission)

    # Assign all permissions to the maintainer group
    maintainer_group.permissions.set(permissions)

    print(f"Created maintainer group with {len(permissions)} permissions")


def remove_maintainer_permissions(apps, schema_editor):
    """Remove maintainer group and permissions.

    Args:
        apps: Django apps registry
        schema_editor: Database schema editor
    """
    try:
        maintainer_group = Group.objects.get(name="Maintainers")
        maintainer_group.delete()
        print("Removed maintainer group")
    except Group.DoesNotExist:
        pass


class Migration(migrations.Migration):
    """Setup maintainer permissions and groups."""

    dependencies = [
        ("adoration", "0010_remove_old_assignments"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(
            create_maintainer_permissions,
            remove_maintainer_permissions,
        ),
    ]
