# Generated by Django 6.0 on 2026-01-12 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to create MaintainerPeriod model and add periods field to Maintainer."""

    dependencies = [
        ("adoration", "0011_setup_maintainer_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintainerPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "maintainer",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="adoration.maintainer"),
                ),
                ("period", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="adoration.period")),
            ],
        ),
        migrations.AddField(
            model_name="maintainer",
            name="periods",
            field=models.ManyToManyField(through="adoration.MaintainerPeriod", to="adoration.period"),
        ),
        migrations.AddConstraint(
            model_name="maintainerperiod",
            constraint=models.UniqueConstraint(
                fields=("maintainer", "period"), name="maintainer_period_unique_constraint"
            ),
        ),
    ]
