# Generated by Django 6.0 on 2026-01-11 22:03

from django.conf import settings
from django.db import migrations


def populate_default_configs(apps, schema_editor):
    """Populate the Config table with default values from constants.

    Args:
        apps: Django apps registry for accessing models
        schema_editor: Django schema editor for database operations
    """
    Config = apps.get_model("adoration", "Config")

    # Default configuration values to be created
    default_configs = [
        {
            "name": "ASSIGNMENT_LIMIT",
            "value": "2",
            "description": "Default maximum number of assignments per period when no collection-specific limit is set",
        },
        {
            "name": "DEFAULT_FROM_EMAIL",
            "value": getattr(settings, "DEFAULT_FROM_EMAIL", "noreply@example.com"),
            "description": "Default email address used as sender for system emails and notifications",
        },
    ]

    # Create configurations only if they don't exist
    for config_data in default_configs:
        Config.objects.get_or_create(
            name=config_data["name"],
            defaults={
                "value": config_data["value"],
                "description": config_data["description"],
            },
        )


def reverse_populate_default_configs(apps, schema_editor):
    """Remove the default configurations created by this migration.

    Args:
        apps: Django apps registry for accessing models
        schema_editor: Django schema editor for database operations
    """
    Config = apps.get_model("adoration", "Config")

    # Configuration names to remove
    config_names = [
        "ASSIGNMENT_LIMIT",
        "DEFAULT_FROM_EMAIL",
    ]

    # Delete only the configurations created by this migration
    Config.objects.filter(name__in=config_names).delete()


class Migration(migrations.Migration):
    """Migration to populate default configuration values from constants."""

    dependencies = [
        ("adoration", "0012_maintainerperiod_maintainer_periods_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_default_configs,
            reverse_populate_default_configs,
            hints={"target_db": "default"},
        ),
    ]
