# Generated by Django 6.0 on 2026-01-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    """Alter Config name field to include choices."""

    dependencies = [
        ("adoration", "0013_populate_default_config_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="name",
            field=models.CharField(
                choices=[("ASSIGNMENT_LIMIT", "Assignment Limit"), ("DEFAULT_FROM_EMAIL", "Default From Email")],
                max_length=100,
                unique=True,
            ),
        ),
    ]
